---
- hosts: kvm_host
  vars_files:
    - vars/config.yml
    - vars/vm_setting.yml
    - vars/download.yml

  tasks:
    - include_tasks: tasks/kvm_host/cleanup-all.yaml
    - include_tasks: tasks/kvm_host/cleanup-clients.yml

- hosts: base
  become: false
  vars_files:
    - vars/config.yml
  tasks:
    - include_tasks: tasks/base/cleanup-clients.yml
