---
# want fix: maybe we need Implementation of file stat before deletion
- name: remove old clients
  file:
    path: "{{ clients.kvm_host.path }}/{{ item }}"
    state: absent
  with_items:
    - kubectl
    - oc
    - openshift-install
  when:
    - cleanup.bin.kvm_host == true
  ignore_errors: yes
