---
- name: send nginx config to kvm host
  tags: add-workers
  copy:
    src:  "{{ files.base }}/conf/nginx.conf"
    dest: /etc/nginx/nginx.conf
    selevel: s0
    serole: object_r
    setype: httpd_config_t
    seuser: system_u

- name: make nginx ipxe dir
  file:
    path: /usr/share/nginx/html/ipxe
    state: directory
    recurse: yes
    selevel: s0
    serole: object_r
    setype: httpd_sys_content_t
    seuser: system_u
    mode: 0755

- name: make nginx ignitions dir
  file:
    path: /usr/share/nginx/html/openshift/coreos/ignitions
    state: directory
    recurse: yes
    selevel: s0
    serole: object_r
    setype: httpd_sys_content_t
    seuser: system_u
    mode: 0755

- name: send coreos to kvm host
  copy:
    src:  "{{ files.base }}/dependencies/{{ item }}"
    dest: /usr/share/nginx/html/ipxe/
    selevel: s0
    serole: object_r
    setype: httpd_sys_content_t
    seuser: system_u
    mode: 0644
  with_items:
    - "{{ config.coreos_kernel }}"
    - "{{ config.coreos_initramfs }}"
    - "{{ config.coreos_bios }}"

- name: send coreos to kvm host for rootfs
  copy:
    src:  "{{ files.base }}/dependencies/{{ item }}"
    dest: /usr/share/nginx/html/ipxe/
    selevel: s0
    serole: object_r
    setype: httpd_sys_content_t
    seuser: system_u
    mode: 0644
  with_items:
    - "{{ config.coreos_rootfs }}"
  when:
    - openshift.use_rootfs == true

- name: send coreos signature to kvm host
  copy:
    src:  "{{ files.base }}/dependencies/{{ config.coreos_bios }}.sig"
    dest: /usr/share/nginx/html/ipxe/
    selevel: s0
    serole: object_r
    setype: httpd_sys_content_t
    seuser: system_u
  when: openshift.dist == "okd"

- name: send boot.ipxe to kvm host
  copy:
    src:  "{{ files.base }}/conf/{{ item }}"
    dest: /usr/share/nginx/html/ipxe/
    selevel: s0
    serole: object_r
    setype: httpd_sys_content_t
    seuser: system_u
    mode: 0644
  with_items:
    - boot.ipxe.bootstrap
    - boot.ipxe.master
    - boot.ipxe.worker

- name: (re)start nginx daemon
  tags: add-workers
  service:
    name: nginx
    state: restarted

