---
- name: send dnsmasq config to kvm host
  copy:
    src:  "{{ files.base }}/conf/dnsmasq.openshift.conf"
    dest: /etc/dnsmasq.d/openshift.conf
    selevel: s0
    serole: object_r
    setype: dnsmasq_etc_t
    seuser: system_u

- name: send dnsmasq hosts to kvm host
  tags: add-workers
  copy:
    src:  "{{ files.base }}/conf/dnsmasq.hosts.openshift"
    dest: /etc/hosts.openshift
    selevel: s0
    serole: object_r
    setype: net_conf_t
    seuser: system_u

- name: add a new line to /etc/resolv.conf
  lineinfile:
    path: /etc/resolv.conf
    firstmatch: yes
    insertbefore: '^nameserver'
    line: "nameserver {{ kvm_host.ip }}"

- name: (re)start dnsmasq daemon
  tags: add-workers
  service:
    name: dnsmasq
    state: restarted

