---
- name: wait-for install-complete
  tags: [resume-bootstrap, resume-install]
  command: "{{ clients.kvm_host.path }}/openshift-install --dir={{ files.kvm }}/bare-metal wait-for install-complete --log-level={{ openshift.install_debug }}"
  async: 3600
  poll: 0
  register: install_complete_sleeper

- name: 'install-complete - check on async task'
  tags: [resume-bootstrap, resume-install]
  async_status:
    jid: "{{ install_complete_sleeper.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 1200
  delay: 30


