---
- name: make ipxe/boot.ipxe.ROLE
  template:
    src:  templates/ipxe/boot-ipxe-cfg.j2
    dest: "{{ files.base }}/conf/boot.ipxe.{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  with_items:
    - bootstrap
    - master
    - worker

- name: make ipxe/boot.ipxe.ROLE for rootfs
  template:
    src:  templates/ipxe/boot-ipxe-cfg-rootfs.j2
    dest: "{{ files.base }}/conf/boot.ipxe.{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  with_items:
    - bootstrap
    - master
    - worker
  when:
    - openshift.use_rootfs == true

